config/routes.rb
WebcamApp::Application.routes.draw do
  
  resources :photos, :only => [:index, :show, :new, :create] do
    post 'upload', :on => :collection
  end
  
  root :to => redirect("/photos")
  
  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @photo = Photo.new(params[:photo])
    @photo.image = File.new(upload_path)
    @photo.save

    redirect_to @photo
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def index
    @photos = Photo.all
  end

  def upload
    File.open(upload_path, 'wb') do |f|
      f.write request.raw_post
    end
    render :text => "ok"
  end

  private

  def upload_path # is used in upload and create
    File.join(Rails.root, 'tmp', 'photo.jpg')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebcamApp</title>
  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/index.html.erb
<h1>All photos</h1>
<p>
  <% @photos.each do |photo| %>
    <%= link_to image_tag(photo.image.url(:thumb)), photo %>
  <% end %>
</p>
<p>
  <%= link_to "Take a new picture", new_photo_path %>
</p>

app/views/photos/new.html.erb
<div id="webcam"></div>
<script type="text/javascript">
    function onload_complete(msg) {
        // fetch the CSRF meta tag data
        var csrf_param = $('meta[name=csrf-param]').attr('content');
        var csrf_token = $('meta[name=csrf-token]').attr('content');

        // reset the api URL appending the auth token parameter
        webcam.set_api_url('<%= upload_photos_path %>' + '?' + csrf_param + "=" + encodeURI(encodeURI(csrf_token)));
    }

    function upload_complete(msg) {
        if (msg == 'ok') {
            $('#new_photo').show();
            $('#photo_description').focus();
        } else {
            alert('An error occured');
            webcam.reset();
        }
    }

    webcam.set_swf_url('/webcam.swf');
    webcam.set_api_url('<%= upload_photos_path %>');
    webcam.set_quality(90);
    webcam.set_shutter_sound(true, '/shutter.mp3');
    webcam.set_hook('onLoad', 'onload_complete');
    webcam.set_hook('onComplete', 'upload_complete');
    $('#webcam').html(webcam.get_html(640, 480));
</script>
<input type="button" value="Take picture" onclick="webcam.snap();"/>

<%= form_for Photo.new, :html => {:style => "display: none;"} do |f| %>
    <p>
      <%= f.label :description %><br/>
      <%= f.text_field :description %>
    </p>
    <p>
      <%= f.submit "Save the photo" %>
      or <%= link_to "Take another", new_photo_path %>
    </p>
<% end %>

app/views/photos/show.html.erb
<h1>Photo</h1>
<p><%= image_tag @photo.image.url(:medium) %></p>
<p>
  <strong>Description:</strong><br />
  <%=h @photo.description %>
</p>
<p>
  <%= link_to "Take a new picture", new_photo_path %>
  | <%= link_to "See all pictures", photos_path %>
</p>